pipeline {
  agent {
    kubernetes {
      label 'helm-pod'
      containerTemplate {
        name 'helm-pod'
        image 'devk8sops/custom-helm:v1'
        ttyEnabled true
        command 'cat'
      }
    }
  }
  stages {
    stage('Run helm') {
      steps {
        container('helm-pod') {
          sh '''
          mkdir ~/.kube
          sshpass -p "vagrant" scp  -o 'StrictHostKeyChecking no' vagrant@10.0.0.10:/home/vagrant/.kube/config ~/.kube
          pwd
          ls -al
          helm ls -A
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade --install postgresql -f application/postgresql/values.yaml --create-namespace --namespace postgres bitnami/postgresql
          echo "deployed!"
          '''
        }
      }
    }
  }
}
