version: '3'
services:
  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always    
    ports:
      - '8001:8001'
    volumes:
      - redisinsight:/db 
volumes:
   redisinsight:
     driver: local
